namespace : monitoring
configName: grafana-datasources

#Deployment
deployName: grafana
replicaSet: 1
app: grafana
containerName: grafana
containerImage: grafana/grafana:latest
portName: grafana
containerPort: 3000
limitsMemory: "1Gi"
limitsCpu: "1000m"
requestsMemory: 500M
requestsCpu: "500m"
volumeMounts:
  - mountPath: /var/lib/grafana
    name: grafana-storage
  - mountPath: /etc/grafana/provisioning/datasources
    name: grafana-datasources
    readOnly: false
volumes:
  - name: grafana-storage
    emptyDir: {}
  - name: grafana-datasources
    configMap:
        defaultMode: 420
        name: grafana-datasources