# Namespace where Prometheus resources will be deployed
namespace : monitoring
#ClusterRole
clusterrolename: prometheus
rbacRules:
- apiGroups: [""]
  resources:
    - nodes
    - nodes/proxy
    - services
    - endpoints
    - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
    - extensions
  resources:
    - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: default

#Configmap
configmapname: prometheus-server-conf

#Deployment
deployName: prometheus-deployment
replicaSet: 1
deployApp: prometheus-server
containerName: prometheus
containerImage: prom/prometheus
containerPort: 9090
volumeMounts:
  - name: prometheus-config-volume
    mountPath: /etc/prometheus/
  - name: prometheus-storage-volume
    mountPath: /prometheus/
volumeName: prometheus-config-volume
configMap:
  defaultMode: 420
  name: prometheus-server-conf