name: "Workflow - Deploy Platform Tools"

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  ENVIRONMENT_STAGE: "dev"

jobs:
  deploy-platform-tools:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ env.AWS_REGION }}

      # Login to EKS, make sure to switch to the permanent cluster created with terraform once it's up
      - name: Login to EKS - update kubeconfig
        run: aws eks update-kubeconfig --name project-x-eks-dev --region $AWS_REGION

      # Add deployment steps for each tool below
      - name: Deploy metrics-server 
        run: kubectl apply -f metric-server/components.yaml

      - name: Deploy ingress-nginx controller
        run: kubectl apply -f ingress-controller/ingress.yaml

      # add prometheus
      - name: Deploy Prometheus
        run: |
          kubectl get namespace monitoring || kubectl create namespace monitoring 
          helm upgrade --install prometheus ./eks-monitor/helm-chart/prometheus \
            --values ./eks-monitor/helm-chart/prometheus/values/prometheus-values.yaml
       
      # add grafana
      - name: Deploy Grafana
        run: |
          helm upgrade --install grafana ./eks-monitor/helm-chart/grafana \
            --values ./eks-monitor/helm-chart/grafana/values/grafana-values.yaml